version: '3.8'

services:
  db:
    image: postgres:16-bullseye
    hostname: db
    restart: always
    env_file:
      - .db.env
    volumes:
      - ./local-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - db

networks:
  db:
    driver: bridge
